export const THEMES = {
    dark: {
        id: 'dark',
        label: 'VS Code Dark',
        place: {
            fill: '#0f172a',
            stroke: '#38bdf8',
            radius: 25,
            strokeWidth: 2.5,
        },
        transition: {
            fill: '#0f172a',
            stroke: '#f59e0b',
            width: 40,
            height: 40,
            strokeWidth: 2.5,
            rx: 6,
        },
        arc: {
            stroke: '#94a3b8',
            strokeWidth: 2,
        },
        text: {
            label: '#94a3b8',
            token: '#ffffff',
            code: '#e2e8f0',
        },
        syntax: {
            keyword: '#ffdc43',
            arrow: '#ffdc43',
            string: '#5cffc9',
            number: '#63ceff',
            operator: '#94a3b8',
            bracket: '#f187ff',
            punctuation: '#94a3b8',
            identifier: '#e2e8f0',
            attributeKey: '#c7d0dd',
            comment: '#64748b',
        },
        diagnostics: {
            error: '#f87171',
            errorText: '#fca5a5',
            errorBg: 'rgba(248, 113, 113, 0.14)',
            lineBorder: '#f87171',
            active: '#38bdf8',
            activeText: '#bae6fd',
            activeBg: 'rgba(56, 189, 248, 0.12)',
            activeLineBorder: '#38bdf8',
        },
        disabled: {
            stroke: '#334155',
            text: '#475569',
        },
        sidebar: {
            bg: '#0f172a',
            border: '#1e293b',
            inputBg: '#020617',
            inputBorder: '#1e293b',
            resizeHandle: '#1e293b',
            resizeHandleHover: '#38bdf8',
        },
        bg: '#020617',
        grid: '#1e293b',
    },

    monokai: {
        id: 'monokai',
        label: 'Monokai Pro',
        place: {
            fill: '#2d2a2e',
            stroke: '#a9dc76',
            radius: 25,
            strokeWidth: 2.5,
        },
        transition: {
            fill: '#2d2a2e',
            stroke: '#ff6188',
            width: 40,
            height: 40,
            strokeWidth: 2.5,
            rx: 6,
        },
        arc: {
            stroke: '#787878',
            strokeWidth: 2,
        },
        text: {
            label: '#c1c0c0',
            token: '#ffd866',
            code: '#f8f8f2',
        },
        syntax: {
            keyword: '#a9dc76',
            arrow: '#a9dc76',
            string: '#ffd866',
            number: '#b17af8',
            operator: '#c1c0c0',
            bracket: '#78dce8',
            punctuation: '#c1c0c0',
            identifier: '#f8f8f2',
            attributeKey: '#d9d7d7',
            comment: '#5b575e',
        },
        diagnostics: {
            error: '#ff6188',
            errorText: '#ff9eb6',
            errorBg: 'rgba(255, 97, 136, 0.14)',
            lineBorder: '#ff6188',
            active: '#78dce8',
            activeText: '#b4f2ff',
            activeBg: 'rgba(120, 220, 232, 0.12)',
            activeLineBorder: '#78dce8',
        },
        disabled: {
            stroke: '#49454c',
            text: '#5b575e',
        },
        sidebar: {
            bg: '#222124',
            border: '#2d2a2e',
            inputBg: '#19181a',
            inputBorder: '#2d2a2e',
            resizeHandle: '#2d2a2e',
            resizeHandleHover: '#ff6188',
        },
        bg: '#19181a',
        grid: '#222124',
    },

    light: {
        id: 'light',
        label: 'Clean Light',
        place: {
            fill: '#ffffff',
            stroke: '#0284c7',
            radius: 25,
            strokeWidth: 2.5,
        },
        transition: {
            fill: '#ffffff',
            stroke: '#d97706',
            width: 40,
            height: 40,
            strokeWidth: 2.5,
            rx: 6,
        },
        arc: {
            stroke: '#64748b',
            strokeWidth: 2,
        },
        text: {
            label: '#475569',
            token: '#0f172a',
            code: '#1e293b',
        },
        syntax: {
            keyword: '#0284c7',
            arrow: '#0284c7',
            string: '#34a817',
            number: '#d97706',
            operator: '#64748b',
            bracket: '#38bdf8',
            punctuation: '#64748b',
            identifier: '#1e293b',
            attributeKey: '#475569',
            comment: '#94a3b8',
        },
        diagnostics: {
            error: '#ef4444',
            errorText: '#f87171',
            errorBg: 'rgba(239, 68, 68, 0.12)',
            lineBorder: '#ef4444',
            active: '#3b82f6',
            activeText: '#93c5fd',
            activeBg: 'rgba(59, 130, 246, 0.12)',
            activeLineBorder: '#3b82f6',
        },
        disabled: {
            stroke: '#cbd5e1',
            text: '#94a3b8',
        },
        sidebar: {
            bg: '#ffffff',
            border: '#e2e8f0',
            inputBg: '#f8fafc',
            inputBorder: '#cbd5e1',
            resizeHandle: '#e2e8f0',
            resizeHandleHover: '#0284c7',
        },
        bg: '#f8fafc',
        grid: '#e2e8f0',
    },
};